### ISSUE TITLE
Przegląd czujników pomiarowych

### ISSUE THREAD

**Issue by LEGOL2** [LEGOL2/weather-station#1]
Należy wykonać przegląd dostępnych czujników temperatury, ciśnienia i wilgotności. 
* dokładność
* cena
* dostępność bibliotek

**Comment by tominkoooo** [comment]
**Wszystkie 3 naraz:**

[Adafruit BME680](https://botland.com.pl/pl/czujniki-gazow/10872-adafruit-bme680-czujnik-temperatury-wilgotnosci-cisnienia-i-gazu.html?search_query=czujnik+temperatury+wilgotnosci+cisnienia&results=29)
- zasilanie 3,3V/5V,
- wilgotność od 10 % do 90 % RH, 
- ciśnienie od 300 hPa do 1100 hPa, 
- temperatura od -40 °C do 85 °C,
- gaz (???) od 0 IAQ do 500 IAQ,
- I2C lub SPI,
- **Drogi - 129.90 zł + dostawa 9.90 zł**
- Pobór prądu: 3.7 uA przy pomiarze temperatury, wilgotności i ciśnienia z częstotliwością 1Hz. Sleep mode - 0.15 uA.


[Adafruit BME280](https://botland.com.pl/pl/czujniki-temperatury/4633-adafruit-bme280-czujnik-wilgotnosci-temperatury-oraz-cisnienia-110kpa-i2cspi-3-5v.html?search_query=czujnik+temperatury+wilgotnosci+cisnienia&results=29)
- zasilanie 3,3V/5V,
- wilgotność: 10 %RH do 80 %RH, 
- ciśnienie: 300 hPa do 1100 hPa,
- temperatura: -40 °C do 85 °C, 
- I2C lub SPI,
- **115 zł + dostawa 9.90 zł,**
- Pobór prądu: 3.6 uA przy pomiarze temperatury, wilgotności i ciśnienia z częstotliwością 1Hz. Sleep mode - 0.15 uA.


[Waveshare BME280](https://botland.com.pl/pl/czujniki-temperatury/13463-waveshare-bme280-czujnik-wilgotnosci-temperatury-oraz-cisnienia-i2cspi-33v5v.html?search_query=czujnik+temperatury+wilgotnosci+cisnienia&results=29)
- zasilanie 3,3V/5 V,
- wilgotność: od 0 %RH do 100 %RH,
- ciśnienie: 300 hPa do 1100 hPa,
- temperatura: od -40 °C do 85 °C,
- I2C lub SPI,
- **30.90 zł + dostawa 9.90 zł, (?)**
- Pobór prądu: 3.6 uA przy pomiarze temperatury, wilgotności i ciśnienia z częstotliwością 1Hz. Sleep mode - 0.15 uA.
- To jest ten sam czujnik co Adafruit BME280, tylko to nie Adafruit, więc nie jest astronomicznie drogie :) + ma złączkę, nie ma konieczności lutowania


[Grove-BME280](https://botland.com.pl/pl/grove-czujniki-temperatury-wilgotnosci-i-cisnienia/11355-grove-bme280-czujnik-wilgotnosci-temperatury-oraz-cisnienia-110kpa-i2c-3-5v.html?search_query=czujnik+temperatury+wilgotnosci+cisnienia&results=29)
- zasilanie 3,3V/5 V,
- wilgotność: od 0 %RH do 100 %RH,
- ciśnienie: 300 hPa do 1100 hPa,
- temperatura: od -40 °C do 85 °C,
- I2C lub SPI,
- **64.90 zł + dostawa 9.90 zł,**
- Pobór prądu: 3.6 uA przy pomiarze temperatury, wilgotności i ciśnienia z częstotliwością 1Hz. Sleep mode - 0.15 uA. Znowu - to samo co wyżej.

Tu zakończyłem research. Jeśli chodzi o czujniki mierzące 3 wielkości naraz w dużej mierze wszędzie wykorzystywany jest chip BOSCHa BME280. 

[Tutaj link do dokumentacji czujnika.](https://www.waveshare.com/w/upload/9/91/BME280_datasheet.pdf)

**Jeśli chodzi o kupienie czujników osobno:**
Zdecydowanie z własnego doświadczenia do pomiaru temperatury i wilgotności poleciłbym DHT22 lub DHT11. 

[DHT11:](https://botland.com.pl/pl/czujniki-temperatury/9301-czujnik-temperatury-i-wilgotnosci-dht11-60c.html?search_query=DHT&results=10)
- zasilanie 3,3V/5 V,
- wilgotność: od 5 %RH do 95 %RH z dokładnością 4 RH,
- temperatura: od -20 °C do 60 °C z dokładnością 2 °C,
- zwraca dane - podobne do interfejsu one-wire,
- **7.90 zł + dostawa 9.90 zł,**
- Pobór prądu: **średnio 0.2 mA (to już więcej niż 3 in 1 powyżej),**
- Stała czasowa średnio 10s.

[DHT22](https://botland.com.pl/pl/czujniki-temperatury/1612-czujnik-temperatury-i-wilgotnosci-dht22-am2302.html?search_query=DHT&results=10)
- zasilanie 3,3V/6 V,
- wilgotność: od 5 %RH do 95 %RH z dokładnością 2 RH,
- temperatura: od -40 °C do 80 °C z dokładnością 0.5 °C,
- zwraca dane - podobne do interfejsu one-wire,
- **24.90 zł + dostawa 9.90 zł,**
- Pobór prądu: średnio 0.2 mA,
- Stała czasowa średnio 2s.

Jeśli chodzi o czujnik ciśnienia:
Graniczne wartości (wręcz rekordowe) dla ciśnienia atmosferycznego (wg. [Wikipedii](https://pl.wikipedia.org/wiki/Ci%C5%9Bnienie_atmosferyczne)) to:
- minimum 965,2 hPa,
- maksimum 1054 hPa.
Na szczęście wartości te mieszczą się w zakresie pomiarowym rozpatrywanych czujników.

[BMP280](https://botland.com.pl/pl/czujniki-cisnienia/7245-bmp280-cyfrowy-barometr-czujnik-cisnienia-110kpa-i2cspi-33v.html?search_query=czujnik+cisnienia&results=47)
- Napięcie zasilania: 3,3 V,
- zakres pomiarowy: od 300 hPa do 1100 hPa z dokładnością do 1hPa,
- I2C lub SPI,
- ** Cena 19.90 zł + 9.90 zł przesyłka.**
- Pobór prądu: 2.7 uA przy częstotliwości pomiaru 1Hz.

[MPL115A2](https://botland.com.pl/pl/czujniki-cisnienia/958-mpl115a2-cyfrowy-czujnik-cisnienia-115kpa-i2c.html?search_query=czujnik+cisnienia&results=47)
- Zakres pomiarowy: 50 - 115 kPa z dokładnością do 1kPa,
- Napięcie zasilania: 2,4 V - 5,5 V
- Komunikacja: I2C
-** Cena 24 zł + przesyłka 9.90 zł,**
- Pobór prądu: 5 uA przy częstotliwości pomiaru 1Hz.

[Pololu LPS25HB](https://botland.com.pl/pl/czujniki-cisnienia/12988-pololu-lps25hb-czujnik-cisnienia-i-wysokosci-126kpa-i2cspi-25-55v.html?search_query=czujnik+cisnienia&results=47)
- Napięcie zasilania: 2,5 V - 5,5 V
- Pobór prądu: 2 mA
- Interfejs komunikacyjny: I2C (TWI) lub SPI
- Zakres pomiarowy: 26 kPa do 126 kPa
- Wbudowany buffor FIFO
- Dokładność:
        dla temperatury: +20 ~ +60 °C: +/- 0,02 kPa
        dla temperatury: 0 ~ +80 °C: +/- 0,1 kPa
-** Cena 31.50 zł + 9.90 zł przesyłka (już drożej niż 3 w 1 powyżej).**

Moim obiektywnym faworytem jest **Waveshare BME280**. Jest aktualnie dostępny na Botlandzie. Nie patrzyłem na Aliexpress jeśli chodzi o sensory. Wszystkie wyszukiwania zostały przeprowadzone na stronie Botlandu (ze względu na jego szeroki dostępny asortyment). Po zdecydowaniu się na wybór czujnika można porównywać jego ceny w innych sklepach.

Dokładności pomiarowe **Waveshare BME280**:
- Temperatura:
    rozdzielczość: 0,01 °C
    dokładność: ± 1 °C

- Wilgotność:
    rozdzielczość: 0,008 % RH
    dokładność: ± 3 % RH
    czas odpowiedzi: 1 s

- Ciśnienie:
    rozdzielczość: 0,18 Pa
    dokładność: ± 1 hPa
