### ISSUE TITLE
Wybór płytek

### ISSUE THREAD

**Issue by LEGOL2** [LEGOL2/weather-station#2]
Wybór dwóch płytek z rodziny arduino wraz z ich cenami.

**Comment by LEGOL2** [comment]
@wojrut97 friendly reminder

**Comment by LEGOL2** [comment]
@wojrut97 proszę o przegląd do niedzieli. W przyszłym tygodniu musimy już zamówić części

**Comment by wojrut97** [comment]
Wygląda na to, że Uno oraz Nano nie mają przeciwwskazań, żeby korzystać jednocześnie z SPI i I2C. Uno i nano niewiele się różnią od siebie, dlatego ja bym nie kombinował i zamówił do obu stacji Nano, jeśli wyswietlacz na to pozwala.

https://allegro.pl/oferta/nano-v3-0-ch340-atmega328-klon-arduino-zlutowany-8483134314
