### ISSUE TITLE
Wybór modułu komunikacji bezprzewodowej

### ISSUE THREAD

**Issue by LEGOL2** [LEGOL2/weather-station#3]
Przegląd oraz wybór modułu do bezprzewodowej komunikacji. Naszym głównym celem jest długi czas pracy na baterii. Linki do sklepów.

**Comment by LEGOL2** [comment]
@Rajlor friendly reminder

**Comment by LEGOL2** [comment]
@Rajlor proszę o przegląd do niedzieli. W przyszłym tygodniu musimy już zamówić części

**Comment by Rajlor** [comment]
- https://pl.aliexpress.com/item/32806877830.html - LORA 433Mhz
- https://botland.com.pl/pl/moduly-radiowe/3191-modul-radiowy-nadajnik-fs100a-odbiornik-433-mhz.html - fs100A 433MHz
