### ISSUE TITLE
Dobór zasilania

### ISSUE THREAD

**Issue by LEGOL2** [LEGOL2/weather-station#5]
Wybranie odpowiedniego zasilania dla naszych modułów. Moduł zewnętrzny ma być zasilany bateryjnie, a moduł wewnętrzny może być zasilany z sieci.

**Comment by simonreginis** [comment]
Moduł główny będzie podpięty na stałe do zasilania więc w tej kwestii nie ma co się zbytnio zastanawiać - kostka z parametrami pozwalającymi zasilić płytkę (nie wiadomo jeszcze jaka płytka więc dobór trzeba będzie przeprowadzić po wyborze płytki)

Moduł zewnętrzny ma mieć zasilanie bateryjne. Tutaj dobrym wyborem będą akumulatory ładowalne  18650. Mają względnie dużą pojemność i parametry pozwalające zasilić moduł płytki z czujnikami oraz komunikacją. Tutaj podobnie dobór ostateczny zostanie przeprowadzony po wyborze płytki.

Podsumowując:

- **Moduł główny** - *zasilanie z sieci*
- **Moduł zewnętrzny** - *zasilanie akumulatorami Li-Poly 18650 (prawdopodobnie)*
