### ISSUE TITLE
Kontakt z prowadzącym + dokumentacja

### ISSUE THREAD

**Issue by LEGOL2** [LEGOL2/weather-station#6]
@tominkoooo napiszesz mail dotyczący części, a następnie wspomożesz mnie przy dokumentacji.

**Comment by tominkoooo** [comment]
Mail wysłany, odpowiedź którą otrzymałem:
- [Czujnik ](https://botland.com.pl/pl/czujniki-temperatury/13463-waveshare-bme280-czujnik-wilgotnosci-temperatury-oraz-cisnienia-i2cspi-33v5v.html?search_query=czujnik+temperatury+wilgotnosci+cisnienia&results=29) - OK
- [Wyświetlacz ](https://botland.com.pl/pl/wyswietlacze-lcd-tft-i-ips/10754-waveshare-lcd-tft-wyswietlacz-kolorowy-18-128x160px-spi.html)- OK, [propozycja, że ten też jest dobry](https://botland.com.pl/pl/wyswietlacze-alfanumeryczne-i-graficzne/2640-wyswietlacz-lcd-4x20-znakow-niebieski-konwerter-i2c-lcm1602.html),
- Zasilanie wewnętrzne z gniazda i zewnętrzne z baterii LG HG2 3000mAh 30A (albo 20A) - propozycja użycia na próbę baterii do telefonu komórkowego + moduł ładowarki, który ma prowadzący,
- [Moduł WiFi ](https://botland.com.pl/pl/moduly-wifi/5463-modul-wifi-esp-12e-esp8266-black-11-gpio-adc-pcb-antena.html)- w porządku, padła również propozycja zakupienia Arduino od razu z modułem WiFi,
- Arduino - prowadzący mówi, że jest w posiadaniu modułu mini pro i uno, możemy bez problemu skupić się na klonach (podana strona [https://abc-rc.pl/](https://abc-rc.pl/)),
- Filament - taki, jaki wybierzemy, byleby był odporny na warunki atmosferyczne,
- Komunikacja - jeżeli zakupimy [moduł z Aliexpress](https://pl.aliexpress.com/item/32806877830.html?fbclid=IwAR3PpFfI8eCfRsQX5MM_3iMA1hx6k9h-ms-Om1aYR3EZQaTZWsZVEStLYto) to prowadzący mówi, że pokryje koszt zakupu (ze względu na potencjalny brak możliwości otrzymania faktury). [Drugi wariant z Botlandu](https://botland.com.pl/pl/moduly-radiowe/3191-modul-radiowy-nadajnik-fs100a-odbiornik-433-mhz.html?fbclid=IwAR2kcOOpSXPbj0hMA5hW_YYwgsfJQEXiRNe90jKOObDIWDwPJ2mnrcRKkl) też może bezproblemowo spełniać swoją rolę.

Z dodatkowych informacji uzyskanych od prowadzącego - jest w posiadaniu klonów Arduino.
